### PR TITLE
should work to fix #105 by always returning a valid looking email

### LINKED ISSUE #105: TG commit failing with Exception: Problems handling commit history for ontology
Term Genie commit is now failing with the following error message:

"The commit operation did not succeed, exception: Problems handling commit history for ontology: GeneOntology. Cause: Could not execute db update."

### PR DESCRIPTION
**Pull request by nathandunn**
@cmungall  and @kltm  can you take a look.  This is based on @kltm  [comment](https://github.com/geneontology/termgenie/issues/105#issuecomment-265011247).

### CODE REVIEW

**Comment by nathandunn** [comment]
Actually looking here, I think that it is an in-memory constraint only:  http://stackoverflow.com/a/2899828/1739366 

So, I moved the constraint up.

**Comment by kltm** [comment]
Is this PR currently ready for review and merge?

**Comment by kltm** [comment]
Honestly, in this interface, I'm not understanding how there are your three separate commits, but only "1" file changed...

**Comment by nathandunn** [comment]
@kltm  It is ready.  The 3rd commit was a merge from upstream, which had no effect.

**Comment by kltm** [comment]
roll the dice!

**Pull request merged**
